config/routes.rb
Testapp::Application.routes.draw do
  resources :pins

  devise_for :users

  get "pages/home"

  get "pages/about"

  root :to => 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url
  validates :description, presence: true
  
  has_attached_file :image, styles: { medium: "320x240>"}
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }

  def image_remote_url=(url_value)
  	self.image = URI.parse(url_value) unless url_value.blank?
  	super
  end

  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  # association Pinに対して1:nの関係
  has_many :pins , :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # GET /pins
  # GET /pins.json
  before_filter :authenticate_user!, except: [:index]

  def index
    @pins = Pin.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_fb.html.erb
<iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fapps.facebook.com%2Ftest-shindanapp%2F&amp;width&amp;layout=standard&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=80&amp;appId=375566012548588" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:80px;" allowTransparency="true"></iframe>

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "One Month Rails", "http://onemonthrails.com" %>
    by <%= link_to "Mattan Griffel", "http://mattangriffel.com" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="/">Pinterest Bizreach</a>

			<div class="nav-collapse" >
				<ul class="nav" >
					<li><%= link_to "Home", pages_home_path %></li>
					<li><%= link_to "About", pages_about_path %></li>
				</ul>
				<ul class="nav pull-right">
					<% if user_signed_in? %> 
						<li><%= link_to "+ Add", new_pin_path %></li>
						<li><%= link_to ("Edit "+current_user.name), edit_user_registration_path %></li>
						<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li><%= link_to "Login", new_user_session_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header" %>

	<div class="container" >
		<%= render "layouts/fb" %>
		<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>
		<%= yield %>
		<%= render "layouts/footer" %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="center hero-unit">
    <h1>This is Piterest Bizreach</h1>
    <p>developed by <%= link_to 'Tairo Moriyama, Product Director',  "http://onemonthrails.com" %></p>

    <p><%= link_to 'Sign up now!', new_user_registration_path, class: "btn btn-large btn-info" %></p>
</div>

app/views/pins/.index.html.erb
<h1>Listing pins</h1>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @pins.each do |pin| %>
  <tr>
    <td><%= pin.description %></td>
    <td><%= link_to 'Show', pin %></td>
    <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
    <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

</table>

<br />

<%= link_to 'New Pin', new_pin_path, class: "btn btn-info" %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"} ) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload Images" %>
  <%= f.input :image_remote_url, label: "or Enter URL" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>
  
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-info" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image), pin %>
	<p><%= pin.description %></p>
	<p>
		<strong>by <%= pin.user.name %></strong>
		<% if current_user == pin.user %>
			<%= link_to 'Edit', edit_pin_path(pin) %>
			<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</p>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span3 offsec6">
		<div class="well">
			<p><%= image_tag @pin.image(:medium) %></p>
			<p><%= @pin.description %></p>
			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
				<%= link_to 'Back', pins_path %>
			<% end %>
		</div>
	</div>
</div>